import type { ITeacher } from "@/lib/types";

export const TEACHER_AVATARS = {
  male: "/images/teachers/male-teacher.png",
  female: "/images/teachers/female-teacher.png",
} as const;

export const FEATURED_TEACHERS: ITeacher[] = [
  {
    id: "teacher-1",
    slug: "hafez-mawlana-rahmatullah",
    name: "Hafez Mawlana Rahmatullah",
    role: "Senior Tajweed Teacher",
    bio: "Experienced Hafiz specializing in Tajweed and Quran recitation with a patient, step-by-step teaching approach.",
    image: "",
    gender: "male",
    country: "Bangladesh",
    featured: true,
    location: "Gopalganj, Bangladesh",
    qualifications: ["Hafiz", "Tajweed Certification"],
    skills: [
      "Advanced Tajweed instruction",
      "One-to-one live classes",
      "Adult and young learner support",
    ],
    experience: "8+ years teaching Quran online and in-person",
    languages: ["Bengali", "Arabic", "Urdu"],
    courseSlugs: ["tajweed-male", "noorani-qaida"],
  },
  {
    id: "teacher-2",
    slug: "mawlana-farid-ahmed",
    name: "Mawlana Farid Ahmed",
    role: "Quran Hifz Specialist",
    bio: "Dedicated teacher guiding students through complete Quran memorization with structured revision plans.",
    image: "",
    gender: "male",
    country: "Bangladesh",
    featured: true,
    location: "Dhaka, Bangladesh",
    qualifications: ["Hafiz", "Islamic Studies"],
    skills: [
      "Full Quran memorization coaching",
      "Daily revision tracking",
      "Motivational student care",
    ],
    experience: "6+ years in Hifz supervision",
    languages: ["Bengali", "Arabic"],
    courseSlugs: ["quran-hifz-male"],
  },
  {
    id: "teacher-3",
    slug: "ustadha-ayesha-khan",
    name: "Ustadha Ayesha Khan",
    role: "Female Quran Teacher",
    bio: "Certified female teacher for sisters and children with a gentle, encouraging classroom style.",
    image: "",
    gender: "female",
    country: "Bangladesh",
    featured: true,
    location: "Dhaka, Bangladesh",
    qualifications: ["Hafiza", "Tajweed Certification"],
    skills: [
      "Teaching sisters and young girls",
      "Noorani Qaida for beginners",
      "Patient pronunciation correction",
    ],
    experience: "5+ years teaching female students online",
    languages: ["Bengali", "English", "Arabic"],
    courseSlugs: ["noorani-qaida", "tajweed-female"],
  },
  {
    id: "teacher-4",
    slug: "mawlana-ibrahim-hassan",
    name: "Mawlana Ibrahim Hassan",
    role: "Islamic Studies Teacher",
    bio: "Scholar with experience teaching students across the Middle East and guiding non-Arabic speakers.",
    image: "",
    gender: "male",
    country: "Egypt",
    featured: true,
    location: "Cairo, Egypt",
    qualifications: ["Alim", "Quran Teacher Certification"],
    skills: [
      "Tajweed for international students",
      "Arabic language support",
      "Structured lesson planning",
    ],
    experience: "10+ years teaching Quran and Islamic studies",
    languages: ["Arabic", "English", "Urdu"],
    courseSlugs: ["tajweed-male", "free-learning"],
  },
  {
    id: "teacher-5",
    slug: "hafez-yusuf-ali",
    name: "Hafez Yusuf Ali",
    role: "Noorani Qaida Expert",
    bio: "Patient instructor for beginners and young learners starting their Quran journey from the alphabet.",
    image: "",
    gender: "male",
    country: "United Kingdom",
    featured: true,
    location: "London, United Kingdom",
    qualifications: ["Hafiz", "Noorani Qaida Specialist"],
    skills: [
      "Children and beginner instruction",
      "Foundation Arabic reading",
      "Engaging online classroom methods",
    ],
    experience: "7+ years teaching beginners in the UK and online",
    languages: ["English", "Bengali", "Arabic"],
    courseSlugs: ["noorani-qaida", "free-learning"],
  },
];

export const MALE_TEACHERS: ITeacher[] = [
  ...FEATURED_TEACHERS.filter((teacher) => teacher.gender === "male"),
  {
    id: "teacher-m6",
    slug: "mawlana-kamal-uddin",
    name: "Mawlana Kamal Uddin",
    role: "Tajweed Instructor",
    bio: "Specializes in advanced Tajweed rules and fluent recitation for dedicated learners.",
    image: "",
    gender: "male",
    country: "Bangladesh",
    location: "Chittagong, Bangladesh",
    qualifications: ["Hafiz", "Advanced Tajweed"],
    skills: ["Makhraj and Sifaat training", "Recitation improvement"],
    experience: "5+ years",
    languages: ["Bengali", "Arabic"],
    courseSlugs: ["tajweed-male"],
  },
  {
    id: "teacher-m7",
    slug: "hafez-abdullah-chowdhury",
    name: "Hafez Abdullah Chowdhury",
    role: "Hifz Teacher",
    bio: "Guides students through structured Quran memorization programs with weekly progress reviews.",
    image: "",
    gender: "male",
    country: "Bangladesh",
    location: "Sylhet, Bangladesh",
    qualifications: ["Hafiz"],
    skills: ["Hifz planning", "Revision schedules", "Student accountability"],
    experience: "4+ years",
    languages: ["Bengali", "Arabic"],
    courseSlugs: ["quran-hifz-male"],
  },
  {
    id: "teacher-m8",
    slug: "mawlana-tariq-islam",
    name: "Mawlana Tariq Islam",
    role: "Noorani Qaida Teacher",
    bio: "Experienced in teaching children and adult beginners with clear, step-by-step methods.",
    image: "",
    gender: "male",
    country: "UAE",
    location: "Dubai, UAE",
    qualifications: ["Alim", "Quran Teacher"],
    skills: ["Beginner instruction", "Flexible scheduling for expat families"],
    experience: "6+ years",
    languages: ["English", "Arabic", "Urdu"],
    courseSlugs: ["noorani-qaida", "free-learning"],
  },
];

export const FEMALE_TEACHERS: ITeacher[] = [
  ...FEATURED_TEACHERS.filter((teacher) => teacher.gender === "female"),
  {
    id: "teacher-f5",
    slug: "wardah-shehryar",
    name: "Alimah Wardah Shehryar",
    role: "Alimah | Quran Teacher",
    bio: "Dedicated Quran teacher committed to helping sisters and children learn with care, clarity, and Islamic adab.",
    about:
      "Assalamu Alaikum. I am Alimah Wardah Shehryar, a Quran teacher dedicated to helping students learn the Book of Allah with love, patience, and proper methodology. I believe every student deserves a teacher who listens, guides, and celebrates small victories on the path of Quran learning.",
    image: "",
    gender: "female",
    country: "Pakistan",
    location: "Rawalpindi, Pakistan",
    dateOfBirth: "13 June 2002",
    age: "23 years old",
    address: "Khaiban-e-Sirsyed, Rawalpindi, Pakistan",
    qualifications: ["Alimah", "B.A."],
    skills: [
      "Teaching for children and female students",
      "Step-by-step method of teaching the Quran",
      "Caring and compassionate behavior towards students",
    ],
    experience: "2 years of experience in teaching Quran",
    languages: ["Urdu", "English"],
    courseSlugs: ["tajweed-female", "noorani-qaida", "quran-hifz-female"],
  },
  {
    id: "teacher-f6",
    slug: "ustadha-fatima-rahman",
    name: "Ustadha Fatima Rahman",
    role: "Tajweed Teacher (Female)",
    bio: "Certified in Tajweed with years of teaching experience for sisters across Bangladesh and abroad.",
    image: "",
    gender: "female",
    country: "Bangladesh",
    location: "Dhaka, Bangladesh",
    qualifications: ["Hafiza", "Tajweed Certification"],
    skills: ["Female-only classes", "Tajweed rules", "Recitation correction"],
    experience: "5+ years",
    languages: ["Bengali", "English", "Arabic"],
    courseSlugs: ["tajweed-female"],
  },
  {
    id: "teacher-f7",
    slug: "ustadha-maryam-siddique",
    name: "Ustadha Maryam Siddique",
    role: "Quran Teacher for Children",
    bio: "Patient and caring instructor for young girls and children beginning their Quran education.",
    image: "",
    gender: "female",
    country: "Bangladesh",
    location: "Gopalganj, Bangladesh",
    qualifications: ["Hafiza", "Child Education Training"],
    skills: [
      "Children's Quran classes",
      "Interactive learning",
      "Parent updates",
    ],
    experience: "4+ years",
    languages: ["Bengali", "Arabic"],
    courseSlugs: ["noorani-qaida", "tajweed-female"],
  },
  {
    id: "teacher-f8",
    slug: "ustadha-khadija-akter",
    name: "Ustadha Khadija Akter",
    role: "Hifz Teacher (Female)",
    bio: "Supports sisters in Quran memorization with personalized plans and consistent follow-up.",
    image: "",
    gender: "female",
    country: "Malaysia",
    location: "Kuala Lumpur, Malaysia",
    qualifications: ["Hafiza"],
    skills: ["Female Hifz programs", "Revision coaching", "Progress tracking"],
    experience: "3+ years",
    languages: ["Bengali", "English", "Malay"],
    courseSlugs: ["quran-hifz-female"],
  },
  {
    id: "teacher-f9",
    slug: "ustadha-nusrat-jahan",
    name: "Ustadha Nusrat Jahan",
    role: "Islamic Studies Teacher",
    bio: "Teaches foundational Islamic knowledge alongside Quran reading for sisters and families.",
    image: "",
    gender: "female",
    country: "United Kingdom",
    location: "Manchester, United Kingdom",
    qualifications: ["Alimah", "Islamic Studies"],
    skills: [
      "Islamic fundamentals",
      "Quran reading support",
      "Multilingual teaching",
    ],
    experience: "6+ years",
    languages: ["English", "Bengali", "Urdu"],
    courseSlugs: ["tajweed-female", "free-learning"],
  },
];
